var json_19thAveandMissionStops_12 = {
"type": "FeatureCollection",
"name": "19thAveandMissionStops_12",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "19th Ave. & Kirkham St Start", "Latitude": 37.76009, "Longitude": -122.47701, "English Neighborhood": "Sunset District ", "English Primary PoI": "19th Ave. & Kirkham St Start", "English Secondary PoI": "Bus zone", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ End", "Local Secondary PoI": "Warriors Way & 3rd St" }, "geometry": { "type": "Point", "coordinates": [ -122.477005, 37.760093 ] } },
{ "type": "Feature", "properties": { "Name": "19th Ave. & Kirkahm St", "Latitude": 37.76006, "Longitude": -122.47698, "English Neighborhood": "Sunset District", "English Primary PoI": "19th Ave & Kirkham St", "English Secondary PoI": "MUNI Bus zone", "Local Neighborhood": "Sunset District", "Local Primary PoI": "19th Ave & Kirkham St", "Local Secondary PoI": "MUNI Bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.476979, 37.760055 ] } },
{ "type": "Feature", "properties": { "Name": "19th Ave & Winston St", "Latitude": 37.72641, "Longitude": -122.47518, "English Neighborhood": "Stonestown", "English Primary PoI": "19th Ave & Winston St", "English Secondary PoI": "19th Ave next to bus shelter", "Local Neighborhood": "Stonestown", "Local Primary PoI": "19th Ave & Winston St", "Local Secondary PoI": "19th Ave next to bus shelter" }, "geometry": { "type": "Point", "coordinates": [ -122.475181, 37.726407 ] } },
{ "type": "Feature", "properties": { "Name": "Daly City BART Station ", "Latitude": 37.70585, "Longitude": -122.46913, "English Neighborhood": "Daly City", "English Primary PoI": "Daly City BART Station", "English Secondary PoI": "Bus zone", "Local Neighborhood": "Daly City", "Local Primary PoI": "Daly City BART Station", "Local Secondary PoI": "Bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.469126, 37.705847 ] } },
{ "type": "Feature", "properties": { "Name": "Cesar Chavez & Florida St", "Latitude": 37.74845, "Longitude": -122.40952, "English Neighborhood": "Mission District", "English Primary PoI": "Cesar Chavez & Florida St", "English Secondary PoI": "MUNI bus zone", "Local Neighborhood": "Mission District", "Local Primary PoI": "Cesar Chavez & Florida St", "Local Secondary PoI": "MUNI bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.409518, 37.748447 ] } },
{ "type": "Feature", "properties": { "Name": "Folsom St & 20th St", "Latitude": 37.7595, "Longitude": -122.41472, "English Neighborhood": "Mission District", "English Primary PoI": "Folsom St & 20th St", "English Secondary PoI": "Folsom midblock between 19th and 20th", "Local Neighborhood": "Mission District", "Local Primary PoI": "Folsom St & 20th St", "Local Secondary PoI": "Folsom midblock between 19th and 20th" }, "geometry": { "type": "Point", "coordinates": [ -122.414719, 37.759496 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ", "Latitude": 37.76878, "Longitude": -122.38872, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388722, 37.768784 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ End", "Latitude": 37.76882, "Longitude": -122.38882, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ End", "English Secondary PoI": "Warriors Way & 3rd St", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ End", "Local Secondary PoI": "Warriors Way & 3rd St" }, "geometry": { "type": "Point", "coordinates": [ -122.388816, 37.768819 ] } }
]
}
