var json_BerkeleyOaklandStops_18 = {
"type": "FeatureCollection",
"name": "BerkeleyOaklandStops_18",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "North Berkeley BART Station  Start", "Latitude": 37.87361, "Longitude": -122.28305, "English Neighborhood": "North Berkeley", "English Primary PoI": "North Berkeley BART Station  Start", "English Secondary PoI": "Bus zone", "Local Neighborhood": "North Berkeley", "Local Primary PoI": "North Berkeley BART Station  Start", "Local Secondary PoI": "Bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.283052, 37.873605 ] } },
{ "type": "Feature", "properties": { "Name": "North Berkeley BART Station ", "Latitude": 37.87363, "Longitude": -122.28305, "English Neighborhood": "North Berkeley", "English Primary PoI": "North Berkeley BART Station", "English Secondary PoI": "Bus zone", "Local Neighborhood": "North Berkeley", "Local Primary PoI": "North Berkeley BART Station", "Local Secondary PoI": "Bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.283052, 37.873626 ] } },
{ "type": "Feature", "properties": { "Name": "Emeryville Amtrak Station", "Latitude": 37.84022, "Longitude": -122.29156, "English Neighborhood": "Emeryville", "English Primary PoI": "Emeryville Amtrak Station", "English Secondary PoI": "Horton St & 59th St", "Local Neighborhood": "Emeryville", "Local Primary PoI": "Emeryville Amtrak Station", "Local Secondary PoI": "Horton St & 59th St" }, "geometry": { "type": "Point", "coordinates": [ -122.291563, 37.840222 ] } },
{ "type": "Feature", "properties": { "Name": "MacArthur BART Station", "Latitude": 37.82937, "Longitude": -122.26642, "English Neighborhood": "Mosswood", "English Primary PoI": "MacArthur BART Station", "English Secondary PoI": "40th St & MacArthur BART Access Rd", "Local Neighborhood": "Mosswood", "Local Primary PoI": "MacArthur BART Station", "Local Secondary PoI": "40th St & MacArthur BART Access Rd" }, "geometry": { "type": "Point", "coordinates": [ -122.266421, 37.829368 ] } },
{ "type": "Feature", "properties": { "Name": "Broadway & 28th St", "Latitude": 37.81611, "Longitude": -122.26399, "English Neighborhood": "Oakland", "English Primary PoI": "Broadway & 28th St", "English Secondary PoI": "Broadway next to red curb bus stop", "Local Neighborhood": "Oakland", "Local Primary PoI": "Broadway & 28th St", "Local Secondary PoI": "Broadway next to red curb bus stop" }, "geometry": { "type": "Point", "coordinates": [ -122.263986, 37.816108 ] } },
{ "type": "Feature", "properties": { "Name": "19th St BART Station", "Latitude": 37.80855, "Longitude": -122.26865, "English Neighborhood": "Uptown", "English Primary PoI": "19th St BART Station", "English Secondary PoI": "Broadway & 20th", "Local Neighborhood": "Uptown", "Local Primary PoI": "19th St BART Station", "Local Secondary PoI": "Broadway & 20th" }, "geometry": { "type": "Point", "coordinates": [ -122.268646, 37.808548 ] } },
{ "type": "Feature", "properties": { "Name": "West Oakland BART Station", "Latitude": 37.80472, "Longitude": -122.29532, "English Neighborhood": "West Oakland", "English Primary PoI": "West Oakland BART Station", "English Secondary PoI": "Bus zone", "Local Neighborhood": "West Oakland", "Local Primary PoI": "West Oakland BART Station", "Local Secondary PoI": "Bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.295318, 37.80472 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ", "Latitude": 37.76878, "Longitude": -122.38872, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388722, 37.768784 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ End", "Latitude": 37.76885, "Longitude": -122.3884, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ End", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ End", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388401, 37.768851 ] } }
]
}
