var json_DublinWalnutCreekStops_10 = {
"type": "FeatureCollection",
"name": "DublinWalnutCreekStops_10",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Dublin BART Station Start", "Latitude": 37.70288, "Longitude": -121.8994, "English Neighborhood": "Dublin", "English Primary PoI": "Dublin BART Station Start", "English Secondary PoI": "Bus zone", "Local Neighborhood": "Dublin", "Local Primary PoI": "Dublin BART Station Start", "Local Secondary PoI": "Bus zone" }, "geometry": { "type": "Point", "coordinates": [ -121.899402, 37.702882 ] } },
{ "type": "Feature", "properties": { "Name": "Dublin BART Station", "Latitude": 37.70292, "Longitude": -121.89944, "English Neighborhood": "Dublin", "English Primary PoI": "Dublin BART Station", "English Secondary PoI": "Bus Zone", "Local Neighborhood": "Dublin", "Local Primary PoI": "Dublin BART Station", "Local Secondary PoI": "Bus Zone" }, "geometry": { "type": "Point", "coordinates": [ -121.89944, 37.702922 ] } },
{ "type": "Feature", "properties": { "Name": "San Ramon Park & Ride ", "Latitude": 37.75924, "Longitude": -121.96637, "English Neighborhood": "San Ramon", "English Primary PoI": "San Ramon Park & Ride ", "English Secondary PoI": "Parking Lot ", "Local Neighborhood": "San Ramon ", "Local Primary PoI": "San Ramon Park & Ride ", "Local Secondary PoI": "Parking Lot " }, "geometry": { "type": "Point", "coordinates": [ -121.966372, 37.759239 ] } },
{ "type": "Feature", "properties": { "Name": "Walnut Creek BART Station", "Latitude": 37.90559, "Longitude": -122.06874, "English Neighborhood": "Walnut Creek", "English Primary PoI": "Walnut Creek BART Station", "English Secondary PoI": "Inside the parking structure", "Local Neighborhood": "Walnut Creek", "Local Primary PoI": "Walnut Creek BART Station", "Local Secondary PoI": "Inside the parking structure" }, "geometry": { "type": "Point", "coordinates": [ -122.068739, 37.905587 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ", "Latitude": 37.76878, "Longitude": -122.38872, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388722, 37.768784 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ End", "Latitude": 37.76886, "Longitude": -122.38851, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ End", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ End", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388511, 37.76886 ] } }
]
}
