var json_FremontStops_16 = {
"type": "FeatureCollection",
"name": "FremontStops_16",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Fremont Start ", "Latitude": 37.55883, "Longitude": -122.00678, "English Neighborhood": "Fremont ", "English Primary PoI": "Fremont Start ", "English Secondary PoI": "Amtrack Centerville Station ", "Local Neighborhood": "Fremont ", "Local Primary PoI": "Fremont Start ", "Local Secondary PoI": "Amtrack Centerville Station " }, "geometry": { "type": "Point", "coordinates": [ -122.006783, 37.558832 ] } },
{ "type": "Feature", "properties": { "Name": "Fremont ", "Latitude": 37.55886, "Longitude": -122.00679, "English Neighborhood": "Fremont ", "English Primary PoI": "Fremont ", "English Secondary PoI": "AmTrack Centerville Station ", "Local Neighborhood": "Fremont ", "Local Primary PoI": "Fremont ", "Local Secondary PoI": "AmTrack Centerville Station " }, "geometry": { "type": "Point", "coordinates": [ -122.006785, 37.558864 ] } },
{ "type": "Feature", "properties": { "Name": "Tasman Dr & Alder Dr - Milpitas", "Latitude": 37.41406, "Longitude": -121.91612, "English Neighborhood": "Milpitas", "English Primary PoI": "Tasman Dr & Alder Dr - Milpitas", "English Secondary PoI": "VTA Bus Zone", "Local Neighborhood": "Milpitas", "Local Primary PoI": "Tasman Dr & Alder Dr - Milpitas", "Local Secondary PoI": "VTA Bus Zone" }, "geometry": { "type": "Point", "coordinates": [ -121.916123, 37.414062 ] } },
{ "type": "Feature", "properties": { "Name": "Santa Clara St at SAP Center - San Jose", "Latitude": 37.33183, "Longitude": -121.90155, "English Neighborhood": "San Jose", "English Primary PoI": "Santa Clara St at SAP Center - San Jose", "English Secondary PoI": "SAP Center", "Local Neighborhood": "San Jose", "Local Primary PoI": "Santa Clara St at SAP Center - San Jose", "Local Secondary PoI": "SAP Center" }, "geometry": { "type": "Point", "coordinates": [ -121.901554, 37.331832 ] } },
{ "type": "Feature", "properties": { "Name": "Lawrence Caltrain Station - Sunnyvale ", "Latitude": 37.37082, "Longitude": -121.9967, "English Neighborhood": "Sunnyvale ", "English Primary PoI": "Lawrence Caltrain Station - Sunnyvale ", "English Secondary PoI": "Shuttle boarding zone ", "Local Neighborhood": "Sunnyvale ", "Local Primary PoI": "Lawrence Caltrain Station - Sunnyvale ", "Local Secondary PoI": "Shuttle boarding zone " }, "geometry": { "type": "Point", "coordinates": [ -121.996704, 37.370821 ] } },
{ "type": "Feature", "properties": { "Name": "Uber Sunnyvale ", "Latitude": 37.37739, "Longitude": -122.03397, "English Neighborhood": "Sunnyvale ", "English Primary PoI": "Uber Sunnyvale ", "English Secondary PoI": "Yellow curb loading zone ", "Local Neighborhood": "Sunnyvale ", "Local Primary PoI": "Uber Sunnyvale ", "Local Secondary PoI": "Yellow curb loading zone " }, "geometry": { "type": "Point", "coordinates": [ -122.033972, 37.377386 ] } },
{ "type": "Feature", "properties": { "Name": "Redwood Shores Pkwy", "Latitude": 37.52107, "Longitude": -122.25277, "English Neighborhood": "San Mateo ", "English Primary PoI": "Redwood Shores Pkwy", "English Secondary PoI": "Bus stop", "Local Neighborhood": "San Mateo", "Local Primary PoI": "Redwood Shores Pkwy", "Local Secondary PoI": "Bus stop " }, "geometry": { "type": "Point", "coordinates": [ -122.252766, 37.521067 ] } },
{ "type": "Feature", "properties": { "Name": "19th Ave Park & Ride-San Mateo ", "Latitude": 37.55222, "Longitude": -122.29673, "English Neighborhood": "San Mateo", "English Primary PoI": "19th Ave Park & Ride - San Mateo", "English Secondary PoI": "Park & Ride Lot", "Local Neighborhood": "San Mateo", "Local Primary PoI": "19th Ave Park & Ride - San Mateo", "Local Secondary PoI": "Park & Ride Lot" }, "geometry": { "type": "Point", "coordinates": [ -122.296726, 37.552218 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ ", "Latitude": 37.76878, "Longitude": -122.38872, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388722, 37.768784 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ End", "Latitude": 37.76886, "Longitude": -122.3886, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ End", "English Secondary PoI": "3rd St & 16th St", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ End", "Local Secondary PoI": "3rd St & 16th St" }, "geometry": { "type": "Point", "coordinates": [ -122.388601, 37.768855 ] } }
]
}
