var json_GearyStops_2 = {
"type": "FeatureCollection",
"name": "GearyStops_2",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Park Presidio Blvd & Geary Blvd Start", "Latitude": 37.78093, "Longitude": -122.47222, "English Neighborhood": "Richmond District", "English Primary PoI": "Park Presidio Blvd & Geary Blvd", "English Secondary PoI": "MUNI bus zone", "Local Neighborhood": "Richmond District", "Local Primary PoI": "Park Presidio Blvd & Geary Blvd", "Local Secondary PoI": "MUNI bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.47222, 37.780928 ] } },
{ "type": "Feature", "properties": { "Name": "Park Presidio Blvd & Geary Blvd", "Latitude": 37.78089, "Longitude": -122.47221, "English Neighborhood": "Richmond District", "English Primary PoI": "Park Presidio Blvd & Geary Blvd", "English Secondary PoI": "MUNI bus zone", "Local Neighborhood": "Richmond District", "Local Primary PoI": "Park Presidio Blvd & Geary Blvd", "Local Secondary PoI": "MUNI bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.472211, 37.780885 ] } },
{ "type": "Feature", "properties": { "Name": "Arguello St & Geary Blvd", "Latitude": 37.78152, "Longitude": -122.45901, "English Neighborhood": "Richmond District", "English Primary PoI": "Arguello St & Geary Blvd", "English Secondary PoI": "MUNI bus zone", "Local Neighborhood": "Richmond District", "Local Primary PoI": "Arguello St & Geary Blvd", "Local Secondary PoI": "MUNI bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.459008, 37.781515 ] } },
{ "type": "Feature", "properties": { "Name": "Divisadero St & Bush St", "Latitude": 37.78632, "Longitude": -122.44, "English Neighborhood": "Lower Pacific Heights", "English Primary PoI": "Divisadero St & Bush St", "English Secondary PoI": "MUNI bus zone", "Local Neighborhood": "Lower Pacific Heights", "Local Primary PoI": "Divisadero St & Bush St", "Local Secondary PoI": "MUNI bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.440003, 37.786324 ] } },
{ "type": "Feature", "properties": { "Name": "Bush St & Franklin St", "Latitude": 37.78824, "Longitude": -122.42336, "English Neighborhood": "Western Addition", "English Primary PoI": "Bush St & Franklin St", "English Secondary PoI": "Curbside Eastbound", "Local Neighborhood": "Western Addition", "Local Primary PoI": "Bush & Franklin", "Local Secondary PoI": "Curbside Eastbound" }, "geometry": { "type": "Point", "coordinates": [ -122.423358, 37.788243 ] } },
{ "type": "Feature", "properties": { "Name": "Fell St & Market St", "Latitude": 37.77652, "Longitude": -122.41817, "English Neighborhood": "Civic Center", "English Primary PoI": "Fell St & Market St", "English Secondary PoI": "White curb passenger loading zone", "Local Neighborhood": "Civic Center ", "Local Primary PoI": "Fell St & Market St", "Local Secondary PoI": "White curb passenger loading zone " }, "geometry": { "type": "Point", "coordinates": [ -122.418169, 37.77652 ] } },
{ "type": "Feature", "properties": { "Name": "Harrison St & 2nd St", "Latitude": 37.78422, "Longitude": -122.39544, "English Neighborhood": "SOMA", "English Primary PoI": "Harrison St & 2nd St", "English Secondary PoI": "MUNI bus zone", "Local Neighborhood": "SOMA", "Local Primary PoI": "Harrison St & 2nd St", "Local Secondary PoI": "MUNI bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.395439, 37.78422 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ", "Latitude": 37.76878, "Longitude": -122.38872, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388722, 37.768784 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ End", "Latitude": 37.76879, "Longitude": -122.38894, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ End", "English Secondary PoI": "Warriors Way & 3rd St", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ End", "Local Secondary PoI": "Warriors Way & 3rd St" }, "geometry": { "type": "Point", "coordinates": [ -122.388936, 37.768792 ] } }
]
}
