var json_MarinaEmbarcaderoStops_3 = {
"type": "FeatureCollection",
"name": "MarinaEmbarcaderoStops_3",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Lombard & Divisadero Start", "Latitude": 37.79888, "Longitude": -122.44286, "English Neighborhood": "Cow Hollow", "English Primary PoI": "Lombard & Divisadero Start", "English Secondary PoI": "MUNI Bus zone", "Local Neighborhood": "Cow Hollow", "Local Primary PoI": "Lombard & Divisadero Start", "Local Secondary PoI": "MUNI Bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.442864, 37.798879 ] } },
{ "type": "Feature", "properties": { "Name": "Lombard St and Divisadero St", "Latitude": 37.79888, "Longitude": -122.44284, "English Neighborhood": "Cow Hollow", "English Primary PoI": "Lombard St & Divisadero St", "English Secondary PoI": "Lombard next to red curb bus stop", "Local Neighborhood": "Cow Hollow", "Local Primary PoI": "Lombard St & Divisadero St", "Local Secondary PoI": "Lombard next to red curb bus stop" }, "geometry": { "type": "Point", "coordinates": [ -122.442836, 37.798878 ] } },
{ "type": "Feature", "properties": { "Name": "Lombard St & Scott St", "Latitude": 37.79915, "Longitude": -122.44072, "English Neighborhood": "Cow Hollow", "English Primary PoI": "Lombard St & Scott St", "English Secondary PoI": "White Zone", "Local Neighborhood": "Cow Hollow", "Local Primary PoI": "Lombard St & Scott St", "Local Secondary PoI": "White Zone" }, "geometry": { "type": "Point", "coordinates": [ -122.440719, 37.799154 ] } },
{ "type": "Feature", "properties": { "Name": "Lombard St & Franklin St", "Latitude": 37.80103, "Longitude": -122.42593, "English Neighborhood": "Cow Hollow", "English Primary PoI": "Lombard St & Franklin St", "English Secondary PoI": "Lombard next to white curb", "Local Neighborhood": "Cow Hollow", "Local Primary PoI": "Lombard St & Franklin St", "Local Secondary PoI": "Lombard next to white curb" }, "geometry": { "type": "Point", "coordinates": [ -122.425934, 37.801031 ] } },
{ "type": "Feature", "properties": { "Name": "North Point St & Mason St", "Latitude": 37.80652, "Longitude": -122.41355, "English Neighborhood": "North Beach", "English Primary PoI": "North Point St & Mason St", "English Secondary PoI": "North Point next to bus shelter", "Local Neighborhood": "North Beach", "Local Primary PoI": "North Point & Mason", "Local Secondary PoI": "North Point next to bus shelter" }, "geometry": { "type": "Point", "coordinates": [ -122.413545, 37.806522 ] } },
{ "type": "Feature", "properties": { "Name": "Broadway & Front St", "Latitude": 37.79877, "Longitude": -122.40014, "English Neighborhood": "North Beach", "English Primary PoI": "Broadway & Front St", "English Secondary PoI": "White zone", "Local Neighborhood": null, "Local Primary PoI": null, "Local Secondary PoI": null }, "geometry": { "type": "Point", "coordinates": [ -122.400143, 37.79877 ] } },
{ "type": "Feature", "properties": { "Name": "Mission St & Steuart St", "Latitude": 37.793, "Longitude": -122.39343, "English Neighborhood": "Embarcadero", "English Primary PoI": "Mission St & Steuart St", "English Secondary PoI": "White zone midblock between Steuart and Spear", "Local Neighborhood": "Embarcadero", "Local Primary PoI": "Mission St & Steuart St", "Local Secondary PoI": "White zone midblock between Steuart and Spear" }, "geometry": { "type": "Point", "coordinates": [ -122.393427, 37.792995 ] } },
{ "type": "Feature", "properties": { "Name": "Harrison St & The Embarcadero", "Latitude": 37.78931, "Longitude": -122.38871, "English Neighborhood": "The East Cut", "English Primary PoI": "Harrison St & The Embarcadero", "English Secondary PoI": "Red zone on Harrison before Embarcadero", "Local Neighborhood": "The East Cut", "Local Primary PoI": "Harrison St & The Embarcadero", "Local Secondary PoI": "Red zone on Harrison before Embarcadero" }, "geometry": { "type": "Point", "coordinates": [ -122.38871, 37.789308 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ", "Latitude": 37.76878, "Longitude": -122.38872, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388722, 37.768784 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ End", "Latitude": 37.76881, "Longitude": -122.38892, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ End", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ End", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388922, 37.76881 ] } }
]
}
