var json_PanhandleStops_14 = {
"type": "FeatureCollection",
"name": "PanhandleStops_14",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Geary Blvd & Divisadero Street Start", "Latitude": 37.78317, "Longitude": -122.4399, "English Neighborhood": "Lower Pacific Heights ", "English Primary PoI": "Geary Blvd & Divisadero Street ", "English Secondary PoI": "MUNI Bus zone", "Local Neighborhood": "Lower Pacific Heights ", "Local Primary PoI": "Geary Blvd & Divisadero Street Start ", "Local Secondary PoI": "MUNI Bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.439903, 37.783174 ] } },
{ "type": "Feature", "properties": { "Name": "Geary Blvd & Divisadero Street ", "Latitude": 37.78319, "Longitude": -122.43979, "English Neighborhood": "Lower Pacific Heights ", "English Primary PoI": "Geary Blvd & Divisadero St ", "English Secondary PoI": "MUNI Bus zone", "Local Neighborhood": "Lower Pacific Heights ", "Local Primary PoI": "Geary Blvd & Divisadero St ", "Local Secondary PoI": "MUNI Bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.439791, 37.783192 ] } },
{ "type": "Feature", "properties": { "Name": "Divisadero Street & Haight Street ", "Latitude": 37.77104, "Longitude": -122.43712, "English Neighborhood": "Panhandle ", "English Primary PoI": "Divisadero St & Haight St", "English Secondary PoI": "MUNI Bus zone", "Local Neighborhood": "Panhandle ", "Local Primary PoI": "Divisadero St & Haight St ", "Local Secondary PoI": "MUNI Bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.43712, 37.771044 ] } },
{ "type": "Feature", "properties": { "Name": "16th St & Church St", "Latitude": 37.76373, "Longitude": -122.4287, "English Neighborhood": "Castro ", "English Primary PoI": "16th St & church ", "English Secondary PoI": "White passenger zone", "Local Neighborhood": "Castro ", "Local Primary PoI": "16th St & Church St", "Local Secondary PoI": "White passenger zone" }, "geometry": { "type": "Point", "coordinates": [ -122.428695, 37.763727 ] } },
{ "type": "Feature", "properties": { "Name": "Valencia St & 25th St ", "Latitude": 37.75024, "Longitude": -122.42054, "English Neighborhood": "Noe Valley ", "English Primary PoI": "Valencia St & 25th St", "English Secondary PoI": "White zone", "Local Neighborhood": "Noe Valley ", "Local Primary PoI": "Valencia St & 25th St", "Local Secondary PoI": "White zone" }, "geometry": { "type": "Point", "coordinates": [ -122.42054, 37.75024 ] } },
{ "type": "Feature", "properties": { "Name": "30th St & Mission St ", "Latitude": 37.74233, "Longitude": -122.42234, "English Neighborhood": "Mission District", "English Primary PoI": "30th St & Mission St", "English Secondary PoI": "MUNI Bus zone", "Local Neighborhood": "Mission District", "Local Primary PoI": "30th St & Mission St ", "Local Secondary PoI": "MUNI Bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.422336, 37.742331 ] } },
{ "type": "Feature", "properties": { "Name": "Cesar Chavez & Florida St", "Latitude": 37.74824, "Longitude": -122.40983, "English Neighborhood": "Mission District", "English Primary PoI": "Cesar Chavez & Florida St", "English Secondary PoI": "MUNI bus zone", "Local Neighborhood": "Mission District", "Local Primary PoI": "Cesar Chavez & Florida St", "Local Secondary PoI": "MUNI bus zone" }, "geometry": { "type": "Point", "coordinates": [ -122.409832, 37.748244 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ", "Latitude": 37.76878, "Longitude": -122.38872, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388722, 37.768784 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ End", "Latitude": 37.76884, "Longitude": -122.38858, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ End ", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ End ", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.38858, 37.768838 ] } }
]
}
