var json_SouthBayStops_8 = {
"type": "FeatureCollection",
"name": "SouthBayStops_8",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Tasman Blvd & Alder Dr - Milpitas Start", "Latitude": 37.41404, "Longitude": -121.91615, "English Neighborhood": "Milpitas", "English Primary PoI": "Tasman Blvd & Alder Dr - Milpitas Start", "English Secondary PoI": "VTA bus zone", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Tasman Blvd & Alder Dr - Milpitas Start", "Local Secondary PoI": "VTA bus zone" }, "geometry": { "type": "Point", "coordinates": [ -121.916146, 37.414038 ] } },
{ "type": "Feature", "properties": { "Name": "Tasman Dr & Alder Dr - Milpitas", "Latitude": 37.41406, "Longitude": -121.91612, "English Neighborhood": "Milpitas", "English Primary PoI": "Tasman Dr & Alder Dr - Milpitas", "English Secondary PoI": "VTA Bus Zone", "Local Neighborhood": "Milpitas", "Local Primary PoI": "Tasman Dr & Alder Dr - Milpitas", "Local Secondary PoI": "VTA Bus Zone" }, "geometry": { "type": "Point", "coordinates": [ -121.916123, 37.414062 ] } },
{ "type": "Feature", "properties": { "Name": "Warm Springs BART Station - Fremont", "Latitude": 37.50254, "Longitude": -121.93816, "English Neighborhood": "Fremont", "English Primary PoI": "Warm Springs BART Station", "English Secondary PoI": "Passenger loading zone", "Local Neighborhood": "Fremont", "Local Primary PoI": "Warm Springs BART Station", "Local Secondary PoI": "Passenger loading zone" }, "geometry": { "type": "Point", "coordinates": [ -121.93816, 37.502544 ] } },
{ "type": "Feature", "properties": { "Name": "Stevenson Blvd & Farwell Dr - Fremont", "Latitude": 37.52649, "Longitude": -121.98573, "English Neighborhood": "Fremont", "English Primary PoI": "Stevenson Blvd & Farwell Dr - Fremont", "English Secondary PoI": "Curbside", "Local Neighborhood": "Fremont", "Local Primary PoI": "Stevenson Blvd & Farwell Dr - Fremont", "Local Secondary PoI": "Curbside" }, "geometry": { "type": "Point", "coordinates": [ -121.985728, 37.526489 ] } },
{ "type": "Feature", "properties": { "Name": "Hayward BART Station", "Latitude": 37.67064, "Longitude": -122.08772, "English Neighborhood": "Hayward", "English Primary PoI": "Hayward BART Station", "English Secondary PoI": "Greyhound Bus Zone", "Local Neighborhood": "Hayward", "Local Primary PoI": "Hayward BART Station", "Local Secondary PoI": "Greyhound Bus Zone" }, "geometry": { "type": "Point", "coordinates": [ -122.087722, 37.670639 ] } },
{ "type": "Feature", "properties": { "Name": "Jackson St & 3rd St - Oakland", "Latitude": 37.79431, "Longitude": -122.27, "English Neighborhood": "Oakland", "English Primary PoI": "Jackson St & 3rd St - Oakland", "English Secondary PoI": "Jack London Square", "Local Neighborhood": "Oakland", "Local Primary PoI": "Jackson  St & 3rd St - Oakland", "Local Secondary PoI": "Jack London Square" }, "geometry": { "type": "Point", "coordinates": [ -122.27, 37.794306 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ", "Latitude": 37.76878, "Longitude": -122.38872, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388722, 37.768784 ] } },
{ "type": "Feature", "properties": { "Name": "Uber HQ End", "Latitude": 37.76884, "Longitude": -122.3886, "English Neighborhood": "Mission Bay", "English Primary PoI": "Uber HQ End", "English Secondary PoI": "Warriors Way & 3rd", "Local Neighborhood": "Mission Bay", "Local Primary PoI": "Uber HQ End", "Local Secondary PoI": "Warriors Way & 3rd" }, "geometry": { "type": "Point", "coordinates": [ -122.388599, 37.768843 ] } }
]
}
